name: publish-nuget

on:
  push:
    branches: [main]       # Auto-versionado en CI
    tags: ['v*']           # Releases estables por tag (v1.2.3)
  workflow_dispatch:       # Para lanzar manualmente

permissions:
  contents: read
  packages: write          # necesario para publicar a GitHub Packages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_PATH: src/UNIR.TFE.Polyrepo.Shared/UNIR.TFE.Polyrepo.Shared.csproj
  TEST_PATH: test/UNIR.TFE.Polyrepo.Shared.Test/UNIR.TFE.Polyrepo.Shared.Test.csproj
  BASE_VERSION: "0.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET + Auth to GH Packages (with cache)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/Directory.Packages.props
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine package version
        id: ver
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"
            echo "RELEASE_KIND=tag" >> $GITHUB_ENV
          else
            VERSION="${BASE_VERSION}.${GITHUB_RUN_NUMBER}"
            echo "RELEASE_KIND=ci" >> $GITHUB_ENV
          fi
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version => ${VERSION}"

      - name: Restore
        run: |
          dotnet restore $PROJECT_PATH \
            --source "https://api.nuget.org/v3/index.json" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet restore $TEST_PATH \
            --source "https://api.nuget.org/v3/index.json" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Build
        run: |
          dotnet build $PROJECT_PATH -c Release --no-restore \
            /p:ContinuousIntegrationBuild=true \
            /p:Version=$PACKAGE_VERSION

      - name: Test (unit tests + coverage)
        run: |
          dotnet test $TEST_PATH -c Release --no-build \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./test-results \
            --collect:"XPlat Code Coverage"

      - name: Test Summary (TRX → Job Summary)
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: ./test-results/*.trx
          reporter: dotnet-trx
          fail-on-errors: true

      # ---- Resumen de cobertura + HTML como artefacto ----
      - name: Generate coverage summary
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: 'test-results/**/coverage.cobertura.xml;**/TestResults/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'MarkdownSummaryGithub;HtmlInline_AzurePipelines'
          assemblyfilters: '+UNIR.TFE.*;-*.Test'

      - name: Add coverage to Job Summary
        if: ${{ hashFiles('coveragereport/SummaryGithub.md') != '' }}
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coveragereport
          if-no-files-found: error
          retention-days: 30

      - name: Upload test results (TRX + cobertura)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./test-results
            **/TestResults/**/*.trx
            **/TestResults/**/coverage.cobertura.xml
          if-no-files-found: error
          retention-days: 30

      - name: Pack
        run: |
          dotnet pack $PROJECT_PATH -c Release -o ./artifacts --no-build \
            /p:Version=$PACKAGE_VERSION \
            /p:PackageVersion=$PACKAGE_VERSION \
            /p:IncludeSymbols=true \
            /p:SymbolPackageFormat=snupkg \
            /p:ContinuousIntegrationBuild=true

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: artifacts/*
          retention-days: 14

      - name: Publish to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --skip-duplicate
          dotnet nuget push "./artifacts/*.snupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --skip-duplicate
