name: publish-nuget
on:
  push:
    tags: ['v*']   # v0.1.0, v1.2.3, etc.

permissions:
  contents: read
  packages: write   # necesario para publicar a GitHub Packages

env:
  PROJECT_PATH: src/UNIR.TFE.Polyrepo.Shared/UNIR.TFE.Polyrepo.Shared.csproj

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Resolve version from tag (drop leading v)
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Pack (inject VERSION)
        run: |
          dotnet restore $PROJECT_PATH
          dotnet pack $PROJECT_PATH -c Release -o ./artifacts \
            /p:Version=$VERSION /p:PackageVersion=$VERSION

      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" --source "github" --skip-duplicate
