name: publish-nuget

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  PROJECT_PATH: src/UNIR.TFE.Polyrepo.Shared/UNIR.TFE.Polyrepo.Shared.csproj
  TEST_PATH: test/UNIR.TFE.Polyrepo.Shared.Test/UNIR.TFE.Polyrepo.Shared.Test.csproj
  BASE_VERSION: "0.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Determine package version
        id: ver
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF_NAME#v}"; echo "RELEASE_KIND=tag" >> $GITHUB_ENV
          else
            VERSION="${BASE_VERSION}.${GITHUB_RUN_NUMBER}"; echo "RELEASE_KIND=ci" >> $GITHUB_ENV
          fi
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version => ${VERSION}"

      - name: Restore
        run: |
          dotnet restore $PROJECT_PATH
          dotnet restore $TEST_PATH

      # --- Fichero de configuración para Coverlet Collector (incluye el assembly de Shared) ---
      - name: Create coverlet runsettings
        run: |
          cat > coverlet.runsettings <<'XML'
          <?xml version="1.0" encoding="utf-8"?>
          <RunSettings>
            <DataCollectionRunSettings>
              <DataCollectors>
                <DataCollector friendlyName="XPlat Code Coverage">
                  <Configuration>
                    <Format>cobertura</Format>
                    <!-- Solo medimos la lib de producción -->
                    <Include>[UNIR.TFE.Polyrepo.Shared*]*</Include>
                    <ExcludeByAttribute>CompilerGeneratedAttribute,GeneratedCodeAttribute</ExcludeByAttribute>
                  </Configuration>
                </DataCollector>
              </DataCollectors>
            </DataCollectionRunSettings>
          </RunSettings>
          XML
          cat coverlet.runsettings

      - name: Test (unit tests + coverage)
        run: |
          dotnet test $TEST_PATH -c Release \
            --logger "trx;LogFileName=test-results.trx" \
            --results-directory ./test-results \
            --settings coverlet.runsettings

      # ---- Resumen de cobertura + HTML como artefacto ----
      - name: Generate coverage summary
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: 'test-results/**/coverage.cobertura.xml;**/TestResults/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'MarkdownSummary;HtmlInline_AzurePipelines'
          assemblyfilters: '+UNIR.TFE.Polyrepo.Shared*'

      - name: Add coverage to Job Summary
        run: |
          echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
          cat coveragereport/Summary.md >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coveragereport

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./test-results
            **/TestResults/**/*.trx
            **/TestResults/**/coverage.cobertura.xml

      - name: Pack
        run: |
          dotnet pack $PROJECT_PATH -c Release -o ./artifacts \
            /p:Version=$PACKAGE_VERSION /p:PackageVersion=$PACKAGE_VERSION

      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" --source "github" --skip-duplicate
